/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Harpreet Singh
 */
public class adminhome extends javax.swing.JFrame {
String hemail,hpassword;
    public adminhome() {
        initComponents();
    }
    public adminhome(String email,String password)
    {
        initComponents();
        hemail=email;
        hpassword=password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        admingallery = new javax.swing.JButton();
        adminsyllabus = new javax.swing.JButton();
        adminquestionpaper = new javax.swing.JButton();
        adminresult = new javax.swing.JButton();
        adminfaculty = new javax.swing.JButton();
        adminnotification = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN PANEL");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 10, 270, 80);

        admingallery.setBackground(new java.awt.Color(255, 255, 255));
        admingallery.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        admingallery.setText("GALLERY");
        admingallery.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        admingallery.setContentAreaFilled(false);
        admingallery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admingallery.setFocusPainted(false);
        admingallery.setFocusable(false);
        admingallery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admingalleryActionPerformed(evt);
            }
        });
        jPanel2.add(admingallery);
        admingallery.setBounds(170, 450, 130, 50);

        adminsyllabus.setBackground(new java.awt.Color(255, 255, 255));
        adminsyllabus.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        adminsyllabus.setText("SYLLABUS");
        adminsyllabus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        adminsyllabus.setContentAreaFilled(false);
        adminsyllabus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminsyllabus.setFocusPainted(false);
        adminsyllabus.setFocusable(false);
        adminsyllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminsyllabusActionPerformed(evt);
            }
        });
        jPanel2.add(adminsyllabus);
        adminsyllabus.setBounds(50, 190, 130, 50);

        adminquestionpaper.setBackground(new java.awt.Color(255, 255, 255));
        adminquestionpaper.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        adminquestionpaper.setText("<html>QUESTION<br />  PAPER</html>"
        );
        adminquestionpaper.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        adminquestionpaper.setContentAreaFilled(false);
        adminquestionpaper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminquestionpaper.setFocusPainted(false);
        adminquestionpaper.setFocusable(false);
        adminquestionpaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminquestionpaperActionPerformed(evt);
            }
        });
        jPanel2.add(adminquestionpaper);
        adminquestionpaper.setBounds(280, 190, 130, 50);

        adminresult.setBackground(new java.awt.Color(255, 255, 255));
        adminresult.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        adminresult.setText("RESULT");
        adminresult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        adminresult.setContentAreaFilled(false);
        adminresult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminresult.setFocusPainted(false);
        adminresult.setFocusable(false);
        adminresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminresultActionPerformed(evt);
            }
        });
        jPanel2.add(adminresult);
        adminresult.setBounds(50, 320, 130, 50);

        adminfaculty.setBackground(new java.awt.Color(255, 255, 255));
        adminfaculty.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        adminfaculty.setText("FACULTY");
        adminfaculty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        adminfaculty.setContentAreaFilled(false);
        adminfaculty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminfaculty.setFocusPainted(false);
        adminfaculty.setFocusable(false);
        adminfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminfacultyActionPerformed(evt);
            }
        });
        jPanel2.add(adminfaculty);
        adminfaculty.setBounds(280, 320, 130, 50);

        adminnotification.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harpreet Singh\\Desktop\\bell-1096279_960_720.png")); // NOI18N
        adminnotification.setBorder(null);
        adminnotification.setContentAreaFilled(false);
        adminnotification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminnotification.setFocusPainted(false);
        adminnotification.setFocusable(false);
        adminnotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminnotificationActionPerformed(evt);
            }
        });
        jPanel2.add(adminnotification);
        adminnotification.setBounds(420, 30, 40, 40);

        backbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harpreet Singh\\Documents\\NetBeansProjects\\project\\returns--button-png-image-80043.png")); // NOI18N
        backbutton.setBorder(null);
        backbutton.setBorderPainted(false);
        backbutton.setContentAreaFilled(false);
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.setFocusPainted(false);
        backbutton.setFocusable(false);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(backbutton);
        backbutton.setBounds(10, 30, 40, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 480, 540);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harpreet Singh\\Documents\\NetBeansProjects\\project\\bg-01.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 520, 584);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 580);

        setSize(new java.awt.Dimension(520, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminsyllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminsyllabusActionPerformed
        this.setVisible(false);
       new adminsyllabus(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_adminsyllabusActionPerformed

    private void adminquestionpaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminquestionpaperActionPerformed
         this.setVisible(false);
       new adminquestionpaper(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_adminquestionpaperActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        this.setVisible(false);
      new Home(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void adminfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminfacultyActionPerformed
        this.setVisible(false);
      new adminfaculty(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_adminfacultyActionPerformed

    private void admingalleryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admingalleryActionPerformed
       this.setVisible(false);
      new admingallery(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_admingalleryActionPerformed

    private void adminnotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminnotificationActionPerformed
       this.setVisible(false);
      new adminnotification(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_adminnotificationActionPerformed

    private void adminresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminresultActionPerformed
      this.setVisible(false);
      new adminresult(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_adminresultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminfaculty;
    private javax.swing.JButton admingallery;
    private javax.swing.JButton adminnotification;
    private javax.swing.JButton adminquestionpaper;
    private javax.swing.JButton adminresult;
    private javax.swing.JButton adminsyllabus;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
