/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Harpreet Singh
 */
public class notification extends javax.swing.JFrame {
    String hemail,hpassword;
    private String notification;

    private notification(String notification) {
       this.notification = notification;
    }
    public notification(String email,String password)
    {
       initComponents();
       PreparedStatement ps;
    ResultSet rs;
    String query = "SELECT notification FROM `admin_notification`";
    ArrayList<notification> notificationList = new ArrayList<>();
    try {
        ps = myconnection.getConnection().prepareStatement(query);
        rs =ps.executeQuery();
        
        while(rs.next())
        {
          notification noti =new notification(rs.getString("notification"));
          notificationList.add(noti);
           //System.out.println(notificationList);
        }
    }   catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    for (int i = 0; i < notificationList.size(); i++) {
            System.out.println(" * "+notificationList.get(i).getnotification());
            jTextArea1_notification.append(" * "+notificationList.get(i).getnotification()+"\n");
    }
        hemail=email;
        hpassword=password;
    }
    public String getnotification() {
    return notification;
}
    public notification() {
        initComponents();
        PreparedStatement ps;
    ResultSet rs;
    String query = "SELECT notification FROM `admin_notification`";
    ArrayList<notification> notificationList = new ArrayList<>();
    try {
        ps = myconnection.getConnection().prepareStatement(query);
        rs =ps.executeQuery();
        
        while(rs.next())
        {
          notification noti =new notification(rs.getString("notification"));
          notificationList.add(noti);
           //System.out.println(notificationList);
        }
    }   catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    for (int i = 0; i < notificationList.size(); i++) {
            System.out.println(" * "+notificationList.get(i).getnotification());
            jTextArea1_notification.append(" * "+notificationList.get(i).getnotification()+"\n");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_notification = new javax.swing.JTextArea();
        backbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setText("Notifications");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(115, 20, 250, 40);

        jScrollPane1.setBorder(null);

        jTextArea1_notification.setEditable(false);
        jTextArea1_notification.setColumns(20);
        jTextArea1_notification.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jTextArea1_notification.setLineWrap(true);
        jTextArea1_notification.setRows(5);
        jTextArea1_notification.setWrapStyleWord(true);
        jTextArea1_notification.setBorder(null);
        jTextArea1_notification.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1_notification);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(16, 70, 450, 450);

        backbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harpreet Singh\\Documents\\NetBeansProjects\\project\\returns--button-png-image-80043.png")); // NOI18N
        backbutton.setBorder(null);
        backbutton.setBorderPainted(false);
        backbutton.setContentAreaFilled(false);
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.setFocusPainted(false);
        backbutton.setFocusable(false);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(backbutton);
        backbutton.setBounds(10, 20, 40, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 480, 540);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harpreet Singh\\Documents\\NetBeansProjects\\project\\bg-01.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 520, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(520, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        this.setVisible(false);
        new Home(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1_notification;
    // End of variables declaration//GEN-END:variables
}
