/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.io.OutputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Harpreet Singh
 */
public class Syllabus extends javax.swing.JFrame {

    String hemail;
    String hpassword;
    public Syllabus() {
        initComponents();
    }
    public Syllabus(String email,String password)
    {
     initComponents();
        hemail=email;
        hpassword=password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        semester8 = new javax.swing.JButton();
        semester1 = new javax.swing.JButton();
        semester2 = new javax.swing.JButton();
        semester3 = new javax.swing.JButton();
        semester4 = new javax.swing.JButton();
        semester5 = new javax.swing.JButton();
        semester6 = new javax.swing.JButton();
        semester7 = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 520, 583));
        setMaximumSize(new java.awt.Dimension(520, 583));
        setMinimumSize(new java.awt.Dimension(520, 583));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEMESTER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 20, 189, 40);

        semester8.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        semester8.setText("VIII");
        semester8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        semester8.setContentAreaFilled(false);
        semester8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester8.setFocusPainted(false);
        semester8.setFocusable(false);
        semester8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester8ActionPerformed(evt);
            }
        });
        jPanel1.add(semester8);
        semester8.setBounds(310, 420, 110, 50);

        semester1.setBackground(new java.awt.Color(255, 255, 255));
        semester1.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        semester1.setText("I");
        semester1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        semester1.setContentAreaFilled(false);
        semester1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester1.setFocusPainted(false);
        semester1.setFocusable(false);
        semester1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester1ActionPerformed(evt);
            }
        });
        jPanel1.add(semester1);
        semester1.setBounds(60, 120, 110, 50);

        semester2.setBackground(new java.awt.Color(255, 255, 255));
        semester2.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        semester2.setText("II");
        semester2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        semester2.setContentAreaFilled(false);
        semester2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester2.setFocusPainted(false);
        semester2.setFocusable(false);
        semester2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester2ActionPerformed(evt);
            }
        });
        jPanel1.add(semester2);
        semester2.setBounds(310, 120, 110, 50);

        semester3.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        semester3.setText("III");
        semester3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        semester3.setContentAreaFilled(false);
        semester3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester3.setFocusPainted(false);
        semester3.setFocusable(false);
        semester3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester3ActionPerformed(evt);
            }
        });
        jPanel1.add(semester3);
        semester3.setBounds(60, 220, 110, 50);

        semester4.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        semester4.setText("IV");
        semester4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        semester4.setContentAreaFilled(false);
        semester4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester4.setFocusPainted(false);
        semester4.setFocusable(false);
        semester4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester4ActionPerformed(evt);
            }
        });
        jPanel1.add(semester4);
        semester4.setBounds(310, 220, 110, 50);

        semester5.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        semester5.setText("V");
        semester5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        semester5.setContentAreaFilled(false);
        semester5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester5.setFocusPainted(false);
        semester5.setFocusable(false);
        semester5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester5ActionPerformed(evt);
            }
        });
        jPanel1.add(semester5);
        semester5.setBounds(60, 320, 110, 50);

        semester6.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        semester6.setText("VI");
        semester6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        semester6.setContentAreaFilled(false);
        semester6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester6.setFocusPainted(false);
        semester6.setFocusable(false);
        semester6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester6ActionPerformed(evt);
            }
        });
        jPanel1.add(semester6);
        semester6.setBounds(310, 320, 110, 50);

        semester7.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        semester7.setText("VII");
        semester7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 134, 244), 3, true));
        semester7.setContentAreaFilled(false);
        semester7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        semester7.setFocusPainted(false);
        semester7.setFocusable(false);
        semester7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semester7ActionPerformed(evt);
            }
        });
        jPanel1.add(semester7);
        semester7.setBounds(60, 420, 110, 50);

        backbutton.setBackground(new java.awt.Color(255, 255, 255));
        backbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harpreet Singh\\Documents\\NetBeansProjects\\project\\returns--button-png-image-80043.png")); // NOI18N
        backbutton.setBorder(null);
        backbutton.setBorderPainted(false);
        backbutton.setContentAreaFilled(false);
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.setFocusPainted(false);
        backbutton.setFocusable(false);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(10, 20, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 480, 540);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harpreet Singh\\Documents\\NetBeansProjects\\project\\bg-01.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setFocusable(false);
        jLabel3.setMaximumSize(new java.awt.Dimension(520, 580));
        jLabel3.setMinimumSize(new java.awt.Dimension(520, 580));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 520, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void semester2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester2ActionPerformed
         String s_number=null;

  PreparedStatement ps;
  ResultSet rs;
  byte[] fileBytes;
String query ="SELECT  `s_url` FROM `admin_syllabus` WHERE s_number=2";
try {
        ps = myconnection.getConnection().prepareStatement(query);
       
        rs =ps.executeQuery();
        
        if(rs.next())
        {
            String season = rs.getString(1);
           // JOptionPane.showMessageDialog(null,season);
            season=season.replace("\\", "\\\\");
            try{
     Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+season);
     }
     catch(Exception ex)
     {
       Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);  
     }  
        }
}
      catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_semester2ActionPerformed

    private void semester1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester1ActionPerformed
        String s_number=null;
//s_number = JOptionPane.showInputDialog("ENTER SEMESTER NUMBER");
  PreparedStatement ps;
  ResultSet rs;
  byte[] fileBytes;
String query ="SELECT  `s_url` FROM `admin_syllabus` WHERE s_number=1";
try {
        ps = myconnection.getConnection().prepareStatement(query);
        rs =ps.executeQuery();
        
        if(rs.next())
        {
            String season = rs.getString(1);
//            JOptionPane.showMessageDialog(null,season);
            season=season.replace("\\", "\\\\");
            try{
     Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+season);
     }
     catch(Exception ex)
     {
       Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);  
     }
           
        }

}
      catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_semester1ActionPerformed

    private void semester3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester3ActionPerformed
        String s_number=null;

  PreparedStatement ps;
  ResultSet rs;
  byte[] fileBytes;
String query ="SELECT  `s_url` FROM `admin_syllabus` WHERE s_number=3";
try {
        ps = myconnection.getConnection().prepareStatement(query);
       
        rs =ps.executeQuery();
        
        if(rs.next())
        {
            String season = rs.getString(1);
           // JOptionPane.showMessageDialog(null,season);
            season=season.replace("\\", "\\\\");
            try{
     Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+season);
     }
     catch(Exception ex)
     {
       Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);  
     }  
        }
}
      catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_semester3ActionPerformed

    private void semester4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester4ActionPerformed
        String s_number=null;

  PreparedStatement ps;
  ResultSet rs;
  byte[] fileBytes;
String query ="SELECT  `s_url` FROM `admin_syllabus` WHERE s_number=4";
try {
        ps = myconnection.getConnection().prepareStatement(query);
       
        rs =ps.executeQuery();
        
        if(rs.next())
        {
            String season = rs.getString(1);
           // JOptionPane.showMessageDialog(null,season);
            season=season.replace("\\", "\\\\");
            try{
     Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+season);
     }
     catch(Exception ex)
     {
       Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);  
     }  
        }
}
      catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_semester4ActionPerformed

    private void semester5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester5ActionPerformed
        String s_number=null;

  PreparedStatement ps;
  ResultSet rs;
  byte[] fileBytes;
String query ="SELECT  `s_url` FROM `admin_syllabus` WHERE s_number=5";
try {
        ps = myconnection.getConnection().prepareStatement(query);
       
        rs =ps.executeQuery();
        
        if(rs.next())
        {
            String season = rs.getString(1);
            //JOptionPane.showMessageDialog(null,season);
            season=season.replace("\\", "\\\\");
            try{
     Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+season);
     }
     catch(Exception ex)
     {
       Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);  
     }  
        }
}
      catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_semester5ActionPerformed

    private void semester6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester6ActionPerformed
        String s_number=null;

  PreparedStatement ps;
  ResultSet rs;
  byte[] fileBytes;
String query ="SELECT  `s_url` FROM `admin_syllabus` WHERE s_number=6";
try {
        ps = myconnection.getConnection().prepareStatement(query);
       
        rs =ps.executeQuery();
        
        if(rs.next())
        {
            String season = rs.getString(1);
           // JOptionPane.showMessageDialog(null,season);
            season=season.replace("\\", "\\\\");
            try{
     Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+season);
     }
     catch(Exception ex)
     {
       Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);  
     }  
        }
}
      catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_semester6ActionPerformed

    private void semester7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester7ActionPerformed
        String s_number=null;

  PreparedStatement ps;
  ResultSet rs;
  byte[] fileBytes;
String query ="SELECT  `s_url` FROM `admin_syllabus` WHERE s_number=7";
try {
        ps = myconnection.getConnection().prepareStatement(query);
       
        rs =ps.executeQuery();
        
        if(rs.next())
        {
            String season = rs.getString(1);
            //JOptionPane.showMessageDialog(null,season);
            season=season.replace("\\", "\\\\");
            try{
     Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+season);
     }
     catch(Exception ex)
     {
       Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);  
     }  
        }
}
      catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_semester7ActionPerformed

    private void semester8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semester8ActionPerformed
       String s_number=null;

  PreparedStatement ps;
  ResultSet rs;
  byte[] fileBytes;
String query ="SELECT  `s_url` FROM `admin_syllabus` WHERE s_number=8";
try {
        ps = myconnection.getConnection().prepareStatement(query);
       
        rs =ps.executeQuery();
        
        if(rs.next())
        {
            String season = rs.getString(1);
            JOptionPane.showMessageDialog(null,season);
            season=season.replace("\\", "\\\\");
            try{
     Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+season);
     }
     catch(Exception ex)
     {
       Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);  
     }  
        }
}
      catch (SQLException ex) {   
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_semester8ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        this.setVisible(false);
        new Home(hemail,hpassword).setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Syllabus().setVisible(true);
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Syllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Syllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Syllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Syllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton semester1;
    private javax.swing.JButton semester2;
    private javax.swing.JButton semester3;
    private javax.swing.JButton semester4;
    private javax.swing.JButton semester5;
    private javax.swing.JButton semester6;
    private javax.swing.JButton semester7;
    private javax.swing.JButton semester8;
    // End of variables declaration//GEN-END:variables
}
